on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - name: Hello world action step
      uses: releaselog/releaselog-action@v0.1
      with:
        api_key: ${{ secrets.releaselog_api_key }}
